### ISSUE TITLE
Running Make

### ISSUE THREAD

**Issue by cameronquatman** [loomnetwork/plasma-indexer#2]
Running make i get:
go: github.com/loomnetwork/yubihsm-go@v0.1.0: parsing go.mod: unexpected module path "github.com/certusone/yubihsm-go"
is there something I'm missing?

**Comment by cameronquatman** [comment]
looks like go-ethereum deleted your branch loomnetwork:secp256k1-normalization , which you still have locally allowing everything to run, but doesn't exist anymore at go-ethereum

**Comment by pathornteng** [comment]
Yes, we use our own branch for this and we will fix our Makefile. In the meantime, you can use our `go-ethereum` branch for compiling this project. Please replace `github.com/ethereum/go-ethereum` with our `github.com/loomnetwork/go-ethereum`

**Comment by pathornteng** [comment]
This issue has been fixed.
